# Generated by Django 2.1.5 on 2019-01-25 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_description', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField(verbose_name='Event date')),
                ('event_time', models.DateTimeField(verbose_name='Event time')),
                ('event_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Country')),
            ],
        ),
    ]
