# Generated by Django 2.1.5 on 2019-01-27 18:18

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20190127_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
