# Generated by Django 2.1.5 on 2019-01-27 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20190127_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['country']},
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_name',
            new_name='country',
        ),
    ]
