# Generated by Django 2.1.5 on 2019-01-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20190127_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(choices=[('AR', 'Argentina'), ('AU', 'Australia'), ('AT', 'Austria'), ('BO', 'Bolivia'), ('BR', 'Brazil'), ('CA', 'Canada'), ('CL', 'Chile'), ('CN', 'China'), ('CO', 'Colombia'), ('IN', 'India'), ('ID', 'Indonesia'), ('MX', 'Mexico'), ('NL', 'Netherlands'), ('ZA', 'South Africa'), ('US', 'United States of America'), ('UY', 'Uruguay')], max_length=3),
        ),
    ]
